// vue/src/App.vue
<script setup>
import Calendar from "./components/Calendar.vue";
</script>

<template>
  <main class="bg-gray-50">
    <div class="container mx-auto px-6">
      <h1 class="text-3xl font-mono underline mb-8">Tailwind CSS Calendar!</h1>
      <Calendar />
    </div>
  </main>
</template>

<style>
#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}
</style>

// react/src/App.tsx
import Calendar from "./Calendar";

function App() {
    return (
        <main className="bg-gray-50">
            <div className="container mx-auto py-16 px-6">
                <h1 className="text-3xl font-mono underline">Tailwind CSS Calendar!</h1>
                <Calendar />
            </div>
        </main>
    )
}

export default App
